# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2023 Olliver Schinagl <oliver@schinagl.nl>

ARG ALPINE_VERSION="latest"
ARG TARGET_ARCH="library"

FROM docker.io/${TARGET_ARCH}/alpine:${ALPINE_VERSION} AS builder

# libdvbdab (DAB/DAB+ in DVB streams), https://github.com/L-S-D/libdvbdab
ARG LIBDVBDAB_REF="e5d36facec5302c7e01841843c6c28a011d4d71d"

WORKDIR /src

COPY . /src/

ENV VUE_FILE_CACHE="/src/.vuecache"
ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"

RUN apk add --no-cache \
        'avahi-dev' \
        'bash' \
        'bsd-compat-headers' \
        'build-base' \
        'cmake' \
        'coreutils' \
        'dbus-dev' \
        'findutils' \
        'gettext-dev' \
        'git' \
        'gnu-libiconv-dev' \
        'libdvbcsa-dev' \
        'libhdhomerun-dev' \
        'linux-headers' \
        'musl-dev' \
        'openssl-dev>3' \
        'pcre2' \
        'pngquant' \
        'pugixml-dev' \
        'py3-requests' \
        'python3' \
        'uriparser-dev' \
        'wget' \
        'zlib-dev' \
    && \
    git config --global --add safe.directory '/src/data/dvb-scan' && \
    sh support/build-libdvbdab.sh "${LIBDVBDAB_REF}" && \
    ./configure \
                --prefix='/usr/local' \
                --disable-doc \
                --disable-execinfo \
                --disable-ffmpeg_static \
                --disable-hdhomerun_static \
                --disable-libfdkaac_static \
                --disable-libmfx_static \
                --disable-libopus_static \
                --disable-libtheora_static \
                --disable-libvorbis_static \
                --disable-libvpx_static \
                --disable-libx264_static \
                --disable-libx265_static \
                --enable-bundle \
                --enable-dvbcsa \
                --enable-dvbdab \
                --enable-hdhomerun_client \
                --enable-kqueue \
                --disable-libav \
                --enable-pngquant \
                --enable-vue_cache \
                --disable-vue_build \
                --python=python3 \
        && \
        make DESTDIR='/tvheadend' -j$(($(nproc) - 1)) install

FROM docker.io/${TARGET_ARCH}/alpine:${ALPINE_VERSION} AS runner

LABEL maintainer="Olliver Schinagl <oliver@schinagl.nl>"

EXPOSE 9981 \
       9982 \
       9983

RUN apk add --no-cache \
        'avahi' \
        'bzip2' \
        'dbus-libs' \
        'gnu-libiconv-libs' \
        'libcrypto3' \
        'libdvbcsa' \
        'libhdhomerun-libs' \
        'libssl3' \
        'libstdc++' \
        'liburiparser' \
        'libva' \
        'libvpx' \
        'mesa' \
        'perl-http-entity-parser' \
        'pngquant' \
        'pcre2' \
        'pugixml' \
        'python3' \
        'tini' \
        'xmltv' \
        'zlib' \
    && \
    addgroup -S 'tvheadend' && \
    adduser -D -G 'tvheadend' -h '/var/lib/tvheadend' -s '/bin/nologin' -S 'tvheadend' && \
    adduser 'tvheadend' 'audio' && \
    adduser 'tvheadend' 'video' && \
    install -d -m 775 -g 'tvheadend' -o 'tvheadend' '/var/lib/tvheadend/recordings' && \
    install -d -m 775 -g 'tvheadend' -o 'tvheadend' '/var/log/tvheadend'

COPY --from=builder "/tvheadend" "/"
COPY "./support/container-entrypoint.sh" "/init"

VOLUME /var/lib/tvheadend
VOLUME /var/lib/tvheadend/recordings
WORKDIR /var/lib/tvheadend/
USER tvheadend

ENTRYPOINT [ "/sbin/tini", "--", "/init" ]
